##################################################
# ORACLE DRIVER
##################################################
BD_ORCL_DRIVER=oracle.jdbc.driver.OracleDriver

##################################################
# CONEXION LOCAL
##################################################
BD_LOCAL_ORCL_USERNAME=NANCY
BD_LOCAL_ORCL_PASSWORD=0219

##################################################
# URL DE CONEXION
##################################################
BD_LOCAL_ORCL_URL=jdbc:oracle:thin:@localhost:1521:XE